# Generated by Django 3.0.5 on 2020-05-09 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Artists', '0022_auto_20200509_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateTimeField()),
                ('death', models.DateTimeField(default='-')),
                ('painting', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=150)),
                ('awards', models.CharField(max_length=200)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artists.Artist')),
            ],
        ),
    ]
