# Generated by Django 3.0.5 on 2020-05-09 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0023_auto_20200509_1028'),
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistblog',
            name='death',
        ),
        migrations.AlterField(
            model_name='artistblog',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artists.Artist'),
        ),
    ]
