# Generated by Django 3.0.5 on 2020-05-10 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0025_auto_20200510_1126'),
        ('Blogs', '0003_auto_20200510_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistblog',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artists.Artist'),
        ),
    ]
