# Generated by Django 3.0.5 on 2020-05-05 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adrress', models.CharField(default='-', max_length=300)),
                ('pincode', models.CharField(default='384265', max_length=7)),
                ('city', models.CharField(choices=[('patan', 'PATAN'), ('amdavad', 'AMDAVAD'), ('vadodara', 'VDODARA'), ('surat', 'SURAT')], default=('patan', 'PATAN'), max_length=50)),
                ('State', models.CharField(choices=[('gujarat', 'GUJARAT'), ('maharasra', 'MAHARASTRA'), ('rajastan', 'RAJASTHAN')], default=('gujarat', 'GUJARAT'), max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
