# Generated by Django 3.0.5 on 2020-05-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='State',
            new_name='state',
        ),
    ]
