# Generated by Django 3.0.5 on 2020-05-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20200505_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='adrress',
            new_name='address',
        ),
    ]
