# Generated by Django 3.0.5 on 2020-05-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artistpainting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paintingname', models.CharField(max_length=50)),
                ('paintingimage', models.ImageField(default='errorimage/noimage.png', upload_to='Image/Artist/')),
                ('paintingtype', models.CharField(max_length=20)),
                ('paintingsize', models.CharField(max_length=50)),
                ('paintingprice', models.IntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artists.Artist')),
            ],
        ),
    ]
