# Generated by Django 3.0.5 on 2020-05-02 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0004_auto_20200502_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paintingcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paintingcategoryname', models.CharField(max_length=50)),
                ('paintingimage', models.ImageField(default='errorimage/noimage.png', upload_to='Image/Category/')),
            ],
        ),
        migrations.AlterField(
            model_name='artistpainting',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artists.Artist'),
        ),
    ]
