# Generated by Django 3.0.5 on 2020-05-02 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0005_auto_20200502_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistpainting',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artists.Artist'),
        ),
        migrations.CreateModel(
            name='Paintingofcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paintingimage', models.ImageField(default='errorimage/noimage.png', upload_to='Image/Category/')),
                ('paintingname', models.CharField(max_length=50)),
                ('paintingsize', models.CharField(max_length=50)),
                ('paintingprice', models.IntegerField(default=0)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artists.Paintingcategory')),
            ],
        ),
    ]
