# Generated by Django 3.0.5 on 2020-05-04 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='buydate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 10, 22, 40, 250447)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 10, 22, 40, 250447)),
        ),
    ]
