# Generated by Django 3.0.5 on 2020-05-04 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0010_auto_20200504_1431'),
        ('Orders', '0003_auto_20200504_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='artistproduct',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Artists.Artistpainting'),
        ),
        migrations.AddField(
            model_name='cart',
            name='categoryproduct',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Artists.Paintingofcategory'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='buydate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 14, 31, 26, 746932)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 14, 31, 26, 745935)),
        ),
    ]
