# Generated by Django 3.0.5 on 2020-05-04 09:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0011_auto_20200504_1452'),
        ('Orders', '0004_auto_20200504_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='buydate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 14, 52, 27, 378209)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='artistproduct',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Artists.Artistpainting'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 14, 52, 27, 378209)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='categoryproduct',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Artists.Paintingofcategory'),
        ),
    ]
