# Generated by Django 3.0.5 on 2020-05-04 09:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0012_auto_20200504_1516'),
        ('Orders', '0005_auto_20200504_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='buydate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 15, 16, 7, 491028)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='artistproduct',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Artists.Artistpainting'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 15, 16, 7, 491028)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='categoryproduct',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Artists.Paintingofcategory'),
        ),
    ]
