# Generated by Django 3.0.5 on 2020-05-05 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_auto_20200504_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='buydate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 13, 1, 10, 230850)),
        ),
        migrations.AlterField(
            model_name='buy',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('confirm', 'CONFIRM')], default=('pending', 'PENDING'), max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 13, 1, 10, 230850)),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
