# Generated by Django 3.0.5 on 2020-05-05 09:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artists', '0014_auto_20200505_1514'),
        ('Orders', '0007_auto_20200505_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='buyproduct',
        ),
        migrations.AddField(
            model_name='buy',
            name='artistproduct',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Artists.Artistpainting'),
        ),
        migrations.AddField(
            model_name='buy',
            name='categoryproduct',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Artists.Paintingofcategory'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='buydate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 15, 14, 20, 268188)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 15, 14, 20, 268188)),
        ),
    ]
