# Generated by Django 3.0.5 on 2020-05-08 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0012_auto_20200506_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='orderid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buy',
            name='buydate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 13, 43, 30, 547698)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 13, 43, 30, 547698)),
        ),
    ]
