# Generated by Django 3.0.5 on 2020-05-08 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0013_auto_20200508_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='buydate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 13, 55, 50, 157020)),
        ),
        migrations.AlterField(
            model_name='buy',
            name='orderid',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 13, 55, 50, 157020)),
        ),
    ]
