# Generated by Django 3.0.5 on 2020-05-09 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0016_auto_20200509_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='buydate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 10, 28, 48, 949711)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 10, 28, 48, 949711)),
        ),
    ]
